# -*- coding: utf-8 -*-
"""iitkHackathon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ajpqY9_7QCX7nCPSC17641LVPMVSPGTn
"""

import math
import numpy as np
import csv
import os
values = []
entries = ['Machine:', 'SizeOfOptionalHeader:', 'Characteristics:', 'MajorLinkerVersion:', 'MinorLinkerVersion:', 'SizeOfCode:', 'SizeOfInitializedData:', 'SizeOfUninitializedData:', 'AddressOfEntryPoint:', 'BaseOfCode:', 'BaseOfData:', 'ImageBase:', 'SectionAlignment:', 'FileAlignment:', 'MajorOperatingSystemVersion:', 'MinorOperatingSystemVersion:', 'MajorImageVersion:', 'MinorImageVersion:', 'MajorSubsystemVersion:', 'MinorSubsystemVersion:', 'SizeOfImage:', 'SizeOfHeaders:', 'CheckSum:', 'Subsystem:', 'DllCharacteristics:', 'SizeOfStackReserve:', 'SizeOfStackCommit:', 'SizeOfHeapReserve:', 'SizeOfHeapCommit:', 'LoaderFlags:', 'NumberOfRvaAndSizes:']
#Sections = ['SectionsNb:', 'SectionsMeanEntropy:', 'SectionsMinEntropy:', 'SectionsMaxEntropy:', 'SectionsMeanRawsize:', 'SectionsMinRawsize:', 'SectionMaxRawsize:', 'SectionsMeanVirtualsize:', 'SectionsMinVirtualsize:', 'SectionMaxVirtualsize:'] 
#Imports = ['ImportsNbDLL:', 'ImportsNb:', 'ImportsNbOrdinal:', 'ExportNb:'] 
#Resources = ['ResourcesNb:', 'ResourcesMeanEntropy:', 'ResourcesMinEntropy:', 'ResourcesMaxEntropy:', 'ResourcesMeanSize:', 'ResourcesMinSize:', 'ResourcesMaxSize:', 'LoadConfigurationSize:', 'VersionInformationSize:'] 


with open("malware.csv", 'w') as csvfile:
  spamwriter = csv.writer(csvfile, delimiter=',', quotechar='|', quoting=csv.QUOTE_MINIMAL)
  header = ['f']*43
  spamwriter.writerow()
  benign_dir = "Static_Analysis_Data/Benign/"
  for file_dir in os.listdir(benign_dir):
    md5 = file_dir
    values.append(md5)
    print(md5)
    entropies = []
    rawsize = []
    virtualsize = []
    dll = 0
    ordinal = 0
    try:
      with open(benign_dir+file_dir+"/Structure_Info.txt") as f:
        data = f.readlines()
        ent = 0
        flag_header = 1
        for line in data:
          words = line.split()
          for i in range(len(words)):
            try:
              if words[i] == entries[ent]:
                values.append(int(words[i+1],16))
                ent += 1
            except:
              pass
              
            if words[i]=="Entropy:":
              entropies.append(words[i+1])
            if words[i]=="SizeOfRawData:":
              rawsize.append(int(words[i+1],16))
            if words[i]=="Misc_VirtualSize:":
              virtualsize.append(int(words[i+1],16))
            if ".dll" in words[i]:
              dll += 1
            elif "Ordinal[" in words[i]:
              ordinal += 1
    except:
      continue

    entropies = np.array(entropies,dtype=np.float32)
    values.append(len(entropies))
    values.append(np.mean(entropies))
    values.append(min(entropies))
    values.append(max(entropies))
    rawsize = np.array(rawsize,dtype=np.float32)
    values.append(np.mean(rawsize))
    values.append(min(rawsize))
    values.append(max(rawsize))
    virtualsize = np.array(virtualsize,dtype=np.float32)
    values.append(np.mean(virtualsize))
    values.append(min(virtualsize))
    values.append(max(virtualsize))
    values.append(dll)
    values.append(ordinal)
    spamwriter.writerow(values)

