# -*- coding: utf-8 -*-
"""extract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C0AAKj3SlotPUr4rvcUux30Uf2QN8q1p
"""

import numpy as np
import os
import json
import csv
from collections import OrderedDict

network = ["tls", "udp", "dns", "http", "icmp", "smtp", "tcp", "hosts", "domains", "irc"]
summary = ["file_created", "file_recreated", "dll_loaded", "file_opened", "file_read", "file_written", "regkey_opened", "regkey_read"]
cat = ["system", "synchronisation", "__notification__", "certificate", "netapi", "file", "misc", "process", "ole", "registry", "services", "network", "resource", "ui", "crypto", "exception", "iexplore"]
def parse_dynamic(dynamic_files):
  output = []
  md5_dynamic = []
  md5_failed_dynamic = []
  for filename in dynamic_files:
    calls = OrderedDict()
    for c in cat:
      calls[c] = 0
    try:
      values = []
      with open(filename) as json_file: 
        data = json.load(json_file)
        values.append(data["info"]["duration"])
        for n in network:
          try:
            values.append(len(data["network"][n]))
          except:
            values.append(0)
        for s in summary:
          try:
            sums = 0
            for g in data["behavior"]["generic"]:
              sums += len(g["summary"][s])
            values.append(sums)
          except:
            values.append(0)
        try:
          values.append(len(data["behavior"]["processes"]))
        except:
          values.append(0)
        for p in data["behavior"]["processes"]:
            c = p["calls"]
            for cats in c:
              calls[cats["category"]] += 1

        for c in calls:
          values.append(calls[c])
      output.append(values)
      md5_dynamic.append(filename[-70:-5])
    except:
      md5_failed_dynamic.append(filename[-70:-5])
  output = np.asarray(output)
  return (md5_dynamic, output, md5_failed_dynamic)



# !7z x /content/drive/My\ Drive/Colab\ Notebooks/Dynamic_Analysis_Dataset_Part2.7z

# from google.colab import drive
# drive.mount('/content/drive')